update Save() to only write data if there are changes
app-sre/vault-manager pull request #133
Opened 2024-12-06 16:16 UTC by jonmosco

Reconciliations are occurring when there are no changes.   Add a check in `Save()` to compare existing roles against new ones to ensure idempotency and avoid unnecessary writes.

2024-12-06 17:27 UTC, TGPSKI requested changes

2024-12-06 17:27 UTC, TGPSKI commented on toplevel/role/role.go
> +func isEqual(existing, new map[string]interface{}) bool {
This method's function is similar in purpose to https://github.com/app-sre/vault-manager/blob/master/pkg/vault/reconcile.go#L29

2024-12-06 17:27 UTC, TGPSKI commented on toplevel/role/role.go
> +	existingData, err := vault.ReadSecret(e.Instance.Address, path, vault.KV_V1)
Save method should be pure, should not read or check validity, that logic should happen in the save caller or elsewhere

2024-12-14 13:55 UTC, jonmosco commented
Closing.  Working on alternative solution as mentioned in comments.

2024-12-14 13:55 UTC, closed without merging