Add logic to push prometheus metrics on each execution
app-sre/vault-manager pull request #76
Opened 2022-09-14 18:43 UTC by dwelch0

This PR adds two custom metrics `vault_manager_reconcile_success` and `vault_manager_duration_seconds` (followed qr metric format of `qontract_reconcile_*`). These metrics are pushed to a push gateway on each execution of vault manager.

`vault_manager_reconcile_success` includes a label for `vault_instance`. This will allow for granular severity alerting when reconciliation of various vault instances fail.

Result of testing against stage push gateway:
![image](https://user-images.githubusercontent.com/100163026/190236255-9a7dcb6e-0b6f-4339-bc13-11f599fae4f7.png)

2022-09-14 19:18 UTC, esron approved these changes

2022-09-14 19:50 UTC, cubismod approved these changes
LGTM

2022-09-14 20:04 UTC, bkez322 requested changes

2022-09-14 20:04 UTC, bkez322 commented on pkg/utils/metrics.go
> +			Help: `Whether or not last reconcile was successful. ` +
```suggestion
			Help: `Whether or not last reconcile for a particular vault instance was successful. ` +
```

2022-09-14 20:04 UTC, bkez322 commented on pkg/utils/metrics.go
> +			Help: "Execution duration of this job in seconds.",
```suggestion
			Help: "Execution duration of this job (reconciling all vault instances) in seconds.",
```

2022-09-14 20:05 UTC, bkez322 commented
Two minor suggestions from me but other LGTM.

2022-09-14 21:49 UTC, merged

2022-09-15 04:30 UTC, geoberle commented
q-r generally exposes metrics regularly via a scrape endpoint and gets scraped via a service monitor. Generally Push gateway has its quirks and should be used only if regular scraping is not an option. What is the reason you decided to use the push gateway for this integration?

2022-09-15 08:12 UTC, rporres commented
I do agree with @geoberle in avoiding the use of Push Gateway as much as possible as it works sometimes unexpectedly and it has a very complicated HA story (we don't have it deployed in HA). Isn't it possible to have a `metrics` endpoint in this integration the same way we have it in the q-r ones?

2022-09-15 14:34 UTC, geoberle commented
@dwelch0 understood. vault-manager is not running as a daemon but within a bash loop that keeps the container alive while running the vault-manager binary occasionally. so no http-server would be running that could be scraped. did i get that right.

what do you think, would it be an option to put the while loop within the vault-manger itself? that would allow you to keep the process running and offering an http-server to scrape?

2022-09-15 14:42 UTC, dwelch0 commented
@geoberle following our slack discussion. Your suggestion on moving the execution loop to main (allowing for a http server to be persisted) seems the clear choice. I will revert this change.